# Generated by Django 4.2.3 on 2023-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tags_articletagspositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='articles', to='articles.tags'),
        ),
        migrations.DeleteModel(
            name='ArticleTagsPositions',
        ),
    ]
