# Generated by Django 4.2.3 on 2023-07-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_tag_articletagspositions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletagspositions',
            old_name='tags',
            new_name='tag',
        ),
    ]
